apiVersion: v1
kind: Service
metadata:
  name: mysql-55-centos7 
  labels:
    run: ipsec-left
    app: mysql-55-centos7
spec:
  selector:
    run: ipsec-left
  type: ClusterIP 
  ports:
   - port: 3306
     targetPort: 80 
     protocol: TCP

