apiVersion: v1
kind: Service
metadata:
  name: mysql-55-centos7
  labels:
    app: mysql-55-centos7
spec:
  selector:
    vpnpod: to-clusterb
  type: ClusterIP
  ports:
   - port: 3306
     targetPort: 100
     protocol: TCP
