apiVersion: v1
kind: Service
metadata:
  name: ipsec-service-right 
  labels:
    run: ipsec-right
spec:
  selector:
    run: ipsec-right
  type: NodePort
  externalTrafficPolicy: Local
  ports:
   - port: 30020
     nodePort: 30021
     targetPort: 30020
     protocol: UDP

