apiVersion: v1
kind: Service
metadata:
  name: kuryr-udp-demo-svc 
  labels:
    run: demo
spec:
  selector:
    run: demo
  type: NodePort
  ports:
   - port: 30000 
     nodePort: 30000
     targetPort: 9090
     protocol: UDP

