apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipsec-left
spec:
  selector:
    matchLabels:
      app: ipsec-left
  replicas: 1
  template:
    metadata:
      labels:
        app: ipsec-left
    spec:
      containers:
      - name: ipsec-left
        image: mangelajo/ipsec-container 
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0
        env:
        - name: REMOTE_IP
          value: 38.145.35.46
        - name: VXLAN_PORT
          value: "31000"
        - name: IPSEC_SIDE
          value: left
        ports:
        - containerPort: 31000 
          protocol: UDP

