apiVersion: v1
kind: Pod 
metadata:
  name: ipsec-left
spec:
  containers:
  - name: ipsec-left
    image: docker.io/mangelajo/ipsec-container 
    env:
    - name: REMOTE_IP
      value: 38.145.35.46
    - name: VXLAN_PORT
      value: "31000"
    - name: IPSEC_SIDE
      value: left 
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
      allowPrivilegeEscalation: true
      privileged: true
      runAsUser: 0
      fsGroup: 0
    ports:
    - containerPort: 31000 
      protocol: UDP
      hostPort: 31000

