apiVersion: v1
kind: Pod 
metadata:
  name: ipsec-right
spec:
  containers:
  - name: ipsec-left
    image: docker.io/mangelajo/ipsec-container 
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
      allowPrivilegeEscalation: true
      privileged: true
      runAsUser: 0
    env:
    - name: REMOTE_IP
      value: 38.145.34.212
    - name: VXLAN_PORT
      value: "31000"
    - name: IPSEC_SIDE
      value: right
    ports:
    - containerPort: 31000
      protocol: UDP
      hostPort: 31000

