apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipsec-right-gce
spec:
  selector:
    matchLabels:
      run: ipsec-right-gce
  replicas: 1
  template:
    metadata:
      labels:
        run: ipsec-right-gce
    spec:
      containers:
      - name: ipsec-right
        image: mangelajo/ipsec-container
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0
        env:
        - name: REMOTE_IP
          value: 104.155.73.191
        - name: VXLAN_PORT
          value: "30024"
        - name: IPSEC_SIDE
          value: right
        ports:
        - containerPort: 30024
          protocol: UDP
        - containerPort: 80
        - containerPort: 81
        - containerPort: 82
        - containerPort: 83
        - containerPort: 84
        - containerPort: 85
        - containerPort: 86
        - containerPort: 87
        - containerPort: 88
        - containerPort: 89
        - containerPort: 90
        - containerPort: 443
        - containerPort: 444
        - containerPort: 445
        - containerPort: 446
        - containerPort: 447
        - containerPort: 448
        - containerPort: 449
        - containerPort: 450
        - containerPort: 451
        - containerPort: 452
        - containerPort: 453
