apiVersion: v1
kind: Service
metadata:
  name: ipsec-service-left 
  labels:
    run: ipsec-left
spec:
  selector:
    run: ipsec-left
  type: NodePort
  externalTrafficPolicy: Local
  ports:
   - port: 30020
     nodePort: 30020
     targetPort: 30021
     protocol: UDP

