apiVersion: v1
kind: Pod 
metadata:
  name: ipsec-left-0
  labels:
    run: ipsec-left 
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: ipsec-left
    image: mangelajo/ipsec-container
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
      allowPrivilegeEscalation: true
      privileged: true
      runAsUser: 0
    env:
    - name: REMOTE_IP
      value: 38.145.35.46
    - name: VXLAN_PORT
      value: "30020"
    - name: IPSEC_SIDE
      value: left
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - ping -W 2 -c 1 169.254.1.2
      initialDelaySeconds: 30
      periodSeconds: 10 
      timeoutSeconds: 3
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - ping -W 2 -c 1 169.254.1.2
      initialDelaySeconds: 5
      periodSeconds: 3 
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 1
    ports:
    - containerPort: 30020
      hostPort: 30020
      protocol: UDP
    - containerPort: 80
    - containerPort: 81
    - containerPort: 82
    - containerPort: 83
    - containerPort: 84
    - containerPort: 85
    - containerPort: 86
    - containerPort: 87
    - containerPort: 88
    - containerPort: 89
    - containerPort: 90
    - containerPort: 443
    - containerPort: 444
    - containerPort: 445
    - containerPort: 446
    - containerPort: 447
    - containerPort: 448
    - containerPort: 449
    - containerPort: 450
    - containerPort: 451
    - containerPort: 452
    - containerPort: 453
